global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets: ["monitoring-node-exporter-server:9100"]

  # tự giám sát chính Prometheus
  - job_name: "prometheus"
    static_configs:
      - targets: ["monitoring-prometheus-server:9090"]

  # giám sát frontend
  - job_name: "frontend"
    metrics_path: /api/metrics
    static_configs:
      - targets: ["web-frontend-server1:3000", "web-frontend-server2:3000"]